name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-15
            platform: mac
            dist: apps/ablocks/dist
            artifacts: |
              apps/ablocks/dist/*.dmg
              apps/ablocks/dist/*.zip
              apps/ablocks/dist/*.blockmap
              apps/ablocks/dist/latest-mac.yml
          - os: windows-latest
            platform: win
            dist: apps/ablocks/dist
            artifacts: |
              apps/ablocks/dist/*.exe
              apps/ablocks/dist/*.blockmap
              apps/ablocks/dist/latest.yml
        
    runs-on: ${{ matrix.os }}

    env:
      NODE_OPTIONS: --max-old-space-size=4096
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build distributable
        run: pnpm dist
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-artifacts
          path: ${{ matrix.artifacts }}
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mac-artifacts/*
            win-artifacts/*
          generate_release_notes: true
